version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip testlambda.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda create-function --function-name github-to-lambda-demo --zip-file fileb://deployment_package.zip -runtime python3.8 --handler lambda_function.lambda_handler 
      - echo "aws lambda get-function --function-name || aws lambda update-function-code --function-name github-to-lambda-demo --zip-file fileb://deployment_package.zip"
      - echo "DONE!!"
